if (typeof(SYNO) === 'undefined') {SYNO = {};}
SYNO.SDS = SYNO.SDS || {};
SYNO.SDS.Session = {
   "SynohdpackStatus" : true,
   "buildphase" : "GM",
   "configured" : true,
   "diskless" : false,
   "dsm_http_port" : 5000,
   "dsm_https_port" : 5001,
   "enable_http_negotiate" : false,
   "enable_syno_token" : "yes",
   "fullversion" : "1629885559",
   "hostname" : "DSM-Host",
   "isLogined" : false,
   "lang" : "enu",
   "login_background_color" : "#FFFFFF",
   "login_background_enable" : false,
   "login_background_ext" : ".jpg",
   "login_background_hd_enable" : false,
   "login_background_pos" : "center",
   "login_background_seq" : 0,
   "login_background_type" : "fromDS",
   "login_enable_fp" : 0,
   "login_logo_enable" : false,
   "login_logo_ext" : ".jpg",
   "login_logo_pos" : "center",
   "login_logo_seq" : 0,
   "login_only_bgcolor" : false,
   "login_style" : "tpl1",
   "login_version_logo" : false,
   "oidc_sso_enable" : false,
   "public_access" : false,
   "sso_appid" : "",
   "sso_default_login" : false,
   "sso_server" : "",
   "sso_support" : false,
   "version" : "1629885559"
}
;
